export const actionTypes = {
    USER_LOGIN: {
        FETCH_REQUEST: 'FETCH_USER_LOGIN_REQUEST',
        FETCH_SUCCESS: 'FETCH_USER_LOGIN_SUCCESS',
        FETCH_FAILURE: 'FETCH_USER_LOGIN_FAILURE',
    },
};