export const actionTypes = {
    USER_DASHBOARD: {
        FETCH_REQUEST: 'FETCH_GET_USER_DASHBOARD_REQUEST',
        FETCH_SUCCESS: 'FETCH_GET_USER_DASHBOARD_SUCCESS',
        FETCH_FAILURE: 'FETCH_GET_USER_DASHBOARD_FAILURE',
    },
};